name: ShellCheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Check-shell-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
      
      - run: echo "check of shell scripts has finished!"



