name: better_md

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  write_better_md:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #install node
      - uses: actions/setup-node@v2
      #install write-good
      - run: npm install -g write-good
      #check md
      - run: write-good *.md
      - run: echo "Done!"
